# Generated by Django 3.1.2 on 2021-02-18 16:31

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='eventInvited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notGoing',
            field=models.ManyToManyField(blank=True, related_name='notGoing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d9d27c6-11f7-4fe0-a066-ad8376c4470a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
