# Generated by Django 3.1.2 on 2021-02-18 16:43

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(blank=True, default=[], related_name='teamManagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, default=[], related_name='teamMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='owners',
            field=models.ManyToManyField(blank=True, default=[], related_name='teamOwners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f80f2346-4d6f-4a9f-b5be-bcf60b0ab0a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
