# Generated by Django 3.1.2 on 2021-02-18 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamAnnouncement', to='main.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9df2fca0-2789-4b4f-939e-9233f749bd70'), editable=False, primary_key=True, serialize=False),
        ),
    ]
