# Generated by Django 3.1.2 on 2021-02-18 17:58

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210218_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='acknowledged',
            field=models.ManyToManyField(blank=True, related_name='userAnnouncementAcknowledgment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3df6329-34e2-4c12-a7e3-e7c09bc8b99b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
