# Generated by Django 3.1.2 on 2021-02-18 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210218_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEvent', to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1f4c108-8787-4e14-a214-4b91aa613289'), editable=False, primary_key=True, serialize=False),
        ),
    ]
