# Generated by Django 3.1.2 on 2021-02-21 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210218_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reactor',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='this is an opus team', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d59a1885-b916-4a85-952f-d236020fe2ec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='TeamMessage',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
