# Generated by Django 3.1.2 on 2021-02-16 15:44

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210120_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cliques',
        ),
        migrations.AddField(
            model_name='clique',
            name='managers',
            field=models.ManyToManyField(related_name='teamManagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clique',
            name='members',
            field=models.ManyToManyField(related_name='teamMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clique',
            name='owners',
            field=models.ManyToManyField(related_name='teamOwners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fb8a3e0-b61c-4d79-ae48-27bcfd8fbb4d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
