# Generated by Django 3.1.2 on 2021-02-16 15:51

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210216_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clique',
            name='managers',
            field=models.ManyToManyField(default=[], related_name='teamManagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clique',
            name='members',
            field=models.ManyToManyField(default=[], related_name='teamMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clique',
            name='owners',
            field=models.ManyToManyField(default=[], related_name='teamOwners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('292eba63-c8e1-46f7-b487-b2c437e78a9b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
