# Generated by Django 3.1.2 on 2021-02-23 02:20

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210222_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='eventInvited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f33c54c3-8d0f-406b-a7da-e0da12741568'), editable=False, primary_key=True, serialize=False),
        ),
    ]
