# Generated by Django 3.1.2 on 2021-02-17 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210216_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cliques',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac599b90-b1d3-4c4d-a3c5-d28a120804b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
