# Generated by Django 3.1.2 on 2021-02-23 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210222_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cb56116-caf7-4d1a-bb6e-34abdc3138bf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
