# Generated by Django 3.1.2 on 2021-02-17 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210216_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68734b8d-71eb-43d2-af87-6c5ebddcb90d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
