# Generated by Django 3.1.2 on 2021-02-18 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a24b2bc-b7ee-4547-b14a-be6e5d6b20ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
